name: finance_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.5.0
  
  # Local Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # UUID Generation
  uuid: ^4.5.1
  
  # Date Formatting
  intl: ^0.19.0
  
  # Equality Comparison
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  riverpod_generator: ^2.5.0

flutter:
  uses-material-design: true
